/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("functional_kotlin.kotlin-application-conventions")
    id("org.jetbrains.dokka") version "1.7.0" apply true
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
}

application {
    // Define the main class for the application.
    mainClass.set("functionalKotlin.app.MainKt")
}

tasks.dokkaHtmlPartial.configure {
    failOnWarning.set(true)

    // dokkaSourceSets {
    // configureEach {
    // includes.from("Module.md")
    // }
    // }
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    kotlinOptions {
        jvmTarget = "17"
    }
}
