name: Code coverage with Codecov.io
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Test Kotlin API
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.4.2
      #cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/release' }}
      with:
        gradle-version: 7.4.2
    - name: Generate Gradle wrapper
      run: gradle wrapper
    - uses: gradle/wrapper-validation-action@v1
    - name: Execute Gradle test
      run: ./gradlew test
    - name: Execute Gradle jacocoTestReport
      run: ./gradlew jacocoTestReport
    - uses: codecov/codecov-action@v3
      with:
        #token: ${{ secrets.CODECOV_TOKEN }}
        #files: ./coverage1.xml,./coverage2.xml # optional
        #flags: unittests # optional
        #name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
